# Generated by Django 4.2.2 on 2023-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], max_length=10, null=True),
        ),
    ]
