# Generated by Django 4.2.2 on 2023-08-12 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(help_text='Enter a unique phone number (minimum 10 digits)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10)]),
        ),
    ]
