# Generated by Django 4.1.7 on 2023-05-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_name',
            new_name='vendor',
        ),
    ]
