# Generated by Django 4.2.2 on 2023-08-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_total_data_order_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_amount', models.IntegerField()),
                ('transaction', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment')),
            ],
        ),
    ]
