# Generated by Django 4.2.2 on 2023-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0002_adminwallet_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='admin_commision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
