# Generated by Django 4.2.2 on 2023-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0003_adminwallet_admin_commision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(max_length=15, unique=True)),
                ('charge_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Charges',
            },
        ),
    ]
