# Generated by Django 4.2.2 on 2023-08-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_charge_data'),
        ('foody', '0004_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_wallet_orders', to='orders.order'),
        ),
    ]
