# Generated by Django 4.2.2 on 2023-08-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_charge_data'),
        ('foody', '0005_adminwallet_created_at_alter_adminwallet_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
