# Generated by Django 4.2.2 on 2023-08-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0007_alter_adminwallet_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
