# Generated by Django 4.2.2 on 2023-08-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0008_transactiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='paid',
            field=models.BooleanField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
