# Generated by Django 4.2.2 on 2023-08-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0009_adminwallet_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminwallet',
            old_name='paid',
            new_name='payment_status',
        ),
    ]
