# Generated by Django 4.2.2 on 2023-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_data_order_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charge_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
